### ISSUE TITLE
Library doesn't seem to work with Arduino Due

### ISSUE THREAD

**Issue by apalazzi** [maniacbug/StandardCplusplus#7]
``` c++
#include <utility.h>
#include <unwind-cxx.h>
#include <system_configuration.h>
#include <StandardCplusplus.h>
#include <vector>
#include <map>

std::vector<int> myvec;
std::map<String, int> mymap;

void setup()
{
  myvec.push_back(1);
  mymap["test"] = 2;
}

void loop() {}
```

When compiling for Arduno Due this gives the following error:

Arduino: 1.5.4 (Windows 7), Board: "Arduino Due (Programming Port)"

In file included from prova_cpp_due.ino:2:
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:176: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:177: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:178: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:179: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:180: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:181: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:182: error: ISO C++ forbids casting to an array type 'char [8]'
C:\Users\andrea\Documents\Arduino\libraries\StandardCplusplus/unwind-cxx.h:183: error: ISO C++ forbids casting to an array type 'char [8]'

**Comment by esel7353** [comment]
I got the same error as fawques, which I was able to cure by adding the extra option -fpermissive to the boards.txt file. But this lead to an error similar to apalazzi encountered.

In file included from /usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/eh_globals.cpp:25:0:
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:176:36: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
 = ((((((((_Unwind_Exception_Class) 'G' 
                                    ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:177:36: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
   << 8 | (_Unwind_Exception_Class) 'N')
                                    ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:178:35: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
  << 8 | (_Unwind_Exception_Class) 'U')
                                   ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:179:41: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
        << 8 | (_Unwind_Exception_Class) 'C')
                                         ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:180:40: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
       << 8 | (_Unwind_Exception_Class) 'C')
                                        ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:181:39: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
      << 8 | (_Unwind_Exception_Class) '+')
                                       ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:182:38: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
     << 8 | (_Unwind_Exception_Class) '+')
                                      ^
/usr/local/share/arduino-1.6.1/libraries/StandardCplusplus/unwind-cxx.h:183:37: error: ISO C++ forbids casting to an array type '_Unwind_Exception_Class {aka char [8]}'
    << 8 | (_Unwind_Exception_Class) '\0');
                                     ^

Has anybody a workaround or a build alternative?

**Comment by esel7353** [comment]
I have the same error as fawques, but after adding the flag -fpermissive to the boards.txt file, the error message turned to something similar to apalazzis message.

Has anybody found a way to fix this (by e.g. an alternative build process)?

**Comment by esel7353** [comment]
I have found a way to get it compiled (probably a very, very bad one). I'm working on ubuntu 14.04 with arduino IDE 1.6.1:

1. open ARDUINO_INSTALLATION/hardware/arduino/sam/boards.txt and add the -fpermissive flag, so that the two lines with "extra_flags" read:

  ```
  arduino_due_x_dbg.build.extra_flags=-fpermissive -D__SAM3X8E__ -mthumb {build.usb_flags}
  ```

  and

  ```
  arduino_due_x.build.extra_flags=-fpermissive -D__SAM3X8E__ -mthumb {build.usb_flags}
  ```

2. open ARDUINO_INSTALLATION/libraries/StandardCplusplus/unwind-cxx.h. Make the lines 175-183 a comment and add the line 

  ```
  const _Unwind_Exception_Class __gxx_exception_class = "GNUCC++\0";
  ```

Honestly I have no idea what I did there (my c++ knowledge is limited). So this might be a very bad workaround.

**Comment by AppliedEM** [comment]
Having the same error with the ESP-12. Has anyone found a workaround that doesn't involve compiling with -fpermissive?

**Comment by mike-matera** [comment]
This project is dead. I have a replacement you can install using the Arduino Library Manager: 

https://github.com/mike-matera/ArduinoSTL

**Comment by maniacbug** [comment]
Fixed now in 41b4465634e34fce8e010386bd80f9a371c6b311. Running great on my Due
